name = "Create Astral"
author = "Laskyyy"
version = "v2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50875d20cfe5256cf677accfa148c8978c6ecbc4ad7249438bb72f80e938db1f"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
