name = "Create Astral"
author = "Laskyyy"
version = "v2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1d3f64b1b6638841853b3a651e5125d8b76350c5761ba2631b09ba8cd4cdaab"

[versions]
fabric = "0.16.3"
minecraft = "1.18.2"
